CREATE TABLE IF NOT EXISTS `car_rentals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_identifier` VARCHAR(64) NOT NULL,
  `owner_name` VARCHAR(128) DEFAULT NULL,
  `renter_identifier` VARCHAR(64) DEFAULT NULL,
  `renter_name` VARCHAR(128) DEFAULT NULL,
  `plate` VARCHAR(16) NOT NULL,
  `vehicle` LONGTEXT NOT NULL,
  `model` VARCHAR(64) DEFAULT NULL,
  `location_index` INT NOT NULL,
  `spawn_position` LONGTEXT NOT NULL,
  `hourly_price` INT NOT NULL DEFAULT 0,
  `rental_start` INT DEFAULT NULL,
  `rental_end` INT DEFAULT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'available',
  `total_price` INT NOT NULL DEFAULT 0,
  `deposit` INT NOT NULL DEFAULT 0,
  `revenue` INT NOT NULL DEFAULT 0,
  `unclaimed_revenue` INT NOT NULL DEFAULT 0,
  `commission` INT NOT NULL DEFAULT 0,
  `tax` INT NOT NULL DEFAULT 0,
  `net_revenue` INT NOT NULL DEFAULT 0,
  `entity_net_id` INT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_plate_status` (`plate`, `status`),
  KEY `idx_owner` (`owner_identifier`),
  KEY `idx_renter` (`renter_identifier`),
  KEY `idx_location_status` (`location_index`, `status`),
  KEY `idx_rental_end` (`rental_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
