CREATE TABLE IF NOT EXISTS `rentcar_rentals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `owner_identifier` varchar(64) NOT NULL,
  `owner_name` varchar(80) NOT NULL,
  `renter_identifier` varchar(64) DEFAULT NULL,
  `renter_name` varchar(80) DEFAULT NULL,
  `plate` varchar(16) NOT NULL,
  `vehicle` longtext NOT NULL,
  `vehicle_label` varchar(80) NOT NULL,
  `spawn_position` longtext NOT NULL,
  `rental_start` bigint DEFAULT NULL,
  `rental_end` bigint DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'available',
  `price_per_hour` int NOT NULL DEFAULT 0,
  `total_price` int NOT NULL DEFAULT 0,
  `deposit` int NOT NULL DEFAULT 10000,
  `revenue` int NOT NULL DEFAULT 0,
  `commission` int NOT NULL DEFAULT 0,
  `tax` int NOT NULL DEFAULT 0,
  `collected` tinyint NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_plate` (`plate`),
  KEY `idx_owner` (`owner_identifier`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
